const CART_TYPE = {
  ADD_TO_CART_ITEM: "ADD_TO_CART_ITEM",
  REMOVE_TO_CART_ITEM: "REMOVE_TO_CART_ITEM",
  DELETE_TO_CART_ITEM: "DELETE_TO_CART_ITEM",
  CHECK_OUT: "CHECK-OUT",
};

export default CART_TYPE;
